plugins {
    id 'java'
    id 'war'
    id 'org.springframework.boot' version '3.3.1'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.spring.coffee'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '21'

ext {
    jdkVersion = '21'
    slf4jVersion = '2.0.13'
    log4jVersion = '2.23.1'
    jacksonVersion = '2.17.2'
    springVersion = '6.1.11'
    springIntegrationVersion = '6.3.1'
    springBatchVersion = '5.1.2'
    springRetryVersion = '2.0.7'
    junitVersion = '5.10.3'
    lombokVersion = '1.18.34'
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot dependencies
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-tomcat'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // For JSP support
    implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
    // compileOnly 'jakarta.servlet:jakarta.servlet-api:4.0.1' // For servlet API support
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl'

    // commons io
    implementation 'commons-io:commons-io:2.11.0'

    // MyBatis
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.3'

    // HikariCP for connection pooling
    implementation 'com.zaxxer:HikariCP:5.1.0'

    // Apache POI for Excel processing
    implementation 'org.apache.poi:poi-ooxml:5.3.0'

    // Diff Utils
    implementation 'io.github.java-diff-utils:java-diff-utils:4.12'

    // Jackson for JSON processing
    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-core:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonVersion}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-csv:${jacksonVersion}"
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // SLF4J
    testImplementation 'org.slf4j:slf4j-simple:2.0.13'


    // jsch for SFTP
    implementation 'com.jcraft:jsch:0.1.55'

    // HTTP client
    implementation 'org.apache.httpcomponents:httpclient:4.5.14'

    // Zip4J for zip file handling
    implementation 'net.lingala.zip4j:zip4j:2.11.5'

    // MyBatis & Spring integration
    // implementation 'org.mybatis:mybatis-spring:3.0.3'
    // implementation 'org.mybatis:mybatis:3.5.16'

    // Jakarta Mail
    implementation 'org.jsoup:jsoup:1.18.1'
    implementation 'org.eclipse.angus:jakarta.mail:2.0.3'

    // jdbc mssql
    implementation 'com.microsoft.sqlserver:mssql-jdbc:12.7.1.jre11-preview'
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-parameters'
}